export const CATEGORIES = [
    {category: 'Management', value: 'Administración'},
    {category: 'Architecture', value: 'Arquitectura'},
    {category: 'Building' , value: 'Construcción'},
    {category: 'Accounting', value: 'Contabilidad'},
    {category: 'Creative', value: 'Creativos'},
    {category: 'Laws', value: 'Derecho y Leyes'},
    {category: 'Education', value: 'Educación'},
    {category: 'Engineering', value: 'Ingeniería'},
    {category: 'Transport', value: 'Logitica y Transportación'},
    {category: 'Manufacturing', value: 'Manufactura'},
    {category: 'Marketing', value: 'Mercadotecnia'},
    {category: 'Human Resources', value: 'Recursos Humanos'},
    {category: 'Healthy', value: 'Salud y Belleza'},
    {category: 'Health Sector', value: 'Sector Salud'},
    {category: 'Technology', value: 'Tecnologia'},
    {category: 'Tourism', value: 'Turismo y Hospitalidad'},
    {category: 'Gastronomy', value: 'Gastronomia'},
    {category: 'Sales', value: 'Ventas'},
    {category: 'Veterinary', value: 'Veterinaria'},
    {category: 'Others', value: 'Otros'}
];